version: '2'
services:

  jenkins:
    build:
      context: .
      dockerfile: Dockerfile
    hostname: jenkins
    container_name: jenkins
    restart: always
    privileged: true
    user: root
    ports:
      - 8083:8080
      - 50003:50000

    volumes:
      - D:\Workspace\docker-volume-data\jenkins-data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - C:\Program Files\Docker\Docker\resources\bin\docker:/usr/bin/docker